name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip3 install gurux-dlms
        pip3 install beautifulsoup4
        pip3 install paho-mqtt
        pip3 install pyserial
        pip3 install cryptography
        pip install influxdb
        pip3 install html5lib
        pip3 install sdnotify
        sudo apt-get install libxslt-dev
        sudo apt install python3-pycryptodome
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
